DATABASE_HOST = 'localhost'
DATABASE_NAME = 'mefmooc'
DATABASE_USER = 'postgres'
DATABASE_PASSWORD = ''
DATABASE_PORT = 5432

ADMIN_USERNAME=''
ADMIN_PASSWORD=''

JWT_ACCESS_TOKEN_EXPIRES=7200
JWT_SECRET_KEY='secret'

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = ""
SMTP_PASSWORD = ""

RABBITMQ_HOST = 'localhost'