from dotenv import load_dotenv
from os import getenv

load_dotenv()

FLASK_HOST = getenv('FLASK_HOST')
FLASK_PORT = getenv('FLASK_PORT')

DATABASE_HOST = getenv('DATABASE_HOST')
DATABASE_NAME = getenv('DATABASE_NAME')
DATABASE_USER = getenv('DATABASE_USER')
DATABASE_PASSWORD = getenv('DATABASE_PASSWORD')
DATABASE_PORT = getenv('DATABASE_PORT')

ADMIN_USERNAME = getenv('ADMIN_USERNAME')
ADMIN_PASSWORD = getenv('ADMIN_PASSWORD')

JWT_ACCESS_TOKEN_EXPIRES = getenv('JWT_ACCESS_TOKEN_EXPIRES')
JWT_SECRET_KEY = getenv('JWT_SECRET_KEY')

SMTP_SERVER = getenv('SMTP_SERVER')
SMTP_PORT = getenv('SMTP_PORT')
SMTP_USERNAME = getenv('SMTP_USERNAME')
SMTP_PASSWORD = getenv('SMTP_PASSWORD')

RABBITMQ_HOST = getenv('RABBITMQ_HOST')