version: '3.5'
services:

  postgres:
    container_name: mefmooc-postgres
    image: postgres
    environment:
      POSTGRES_DB: mefmooc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ay2945349*
    volumes:
      - /Users/yildizah/Documents/GitHub/mef-mooc-backend/postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    restart: always

